[project]
name = "3-hugging-face"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohamad Firas Amin", email = "mohammad.ferasamin@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "datasets>=5.0.1",
    "huggingface-hub>=1.33.0",
    "python-dotenv>=1.2.3",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]

[project.scripts]
3-hugging-face = "3_hugging_face:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
