[project]
name = "5-data-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohamad Firas Amin", email = "mohammad.ferasamin@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "plotly-express>=0.4.1",
    "scipy>=1.18.1",
]

[project.scripts]
5-data-project = "5_data_project:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
